"""empty message

Revision ID: 85780f43f6ea
Revises: 0fed7849a966
Create Date: 2022-06-24 02:40:16.728084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85780f43f6ea'
down_revision = '0fed7849a966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'toe_beans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('toe_beans', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
