"""Add age

Revision ID: 8b3be83544e2
Revises: 9b1843036db0
Create Date: 2021-10-26 10:46:21.556750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3be83544e2'
down_revision = '9b1843036db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'age')
    # ### end Alembic commands ###
